# Generated by Django 4.2.13 on 2026-09-08 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("goods", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trading", "洽谈中"),
                            ("confirmed", "交易确认"),
                            ("completed", "已完成"),
                        ],
                        db_index=True,
                        default="trading",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "buyer_confirmed",
                    models.BooleanField(default=False, verbose_name="买家确认"),
                ),
                (
                    "seller_confirmed",
                    models.BooleanField(default=False, verbose_name="卖家确认"),
                ),
                ("buyer_unread", models.IntegerField(default=0, verbose_name="买家未读数")),
                ("seller_unread", models.IntegerField(default=0, verbose_name="卖家未读数")),
                (
                    "last_message",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="最近消息"
                    ),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="最近消息时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_conversations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="买家",
                    ),
                ),
                (
                    "goods",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="goods.goods",
                        verbose_name="商品",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sell_conversations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="卖家",
                    ),
                ),
            ],
            options={
                "verbose_name": "交易会话",
                "verbose_name_plural": "交易会话",
                "db_table": "swap_conversation",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "msg_type",
                    models.CharField(
                        choices=[("text", "文字"), ("image", "图片"), ("video", "视频")],
                        default="text",
                        max_length=10,
                        verbose_name="消息类型",
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, default="", verbose_name="内容"),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="chat_tmp/", verbose_name="附件"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="发送时间"
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.conversation",
                        verbose_name="会话",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发送者",
                    ),
                ),
            ],
            options={
                "verbose_name": "消息",
                "verbose_name_plural": "消息",
                "db_table": "swap_message",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["trading", "confirmed"])),
                fields=("goods", "buyer"),
                name="unique_active_conv_per_buyer",
            ),
        ),
    ]
