# Generated by Django 4.2.13 on 2026-09-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="status",
            field=models.CharField(
                choices=[
                    ("trading", "洽谈中"),
                    ("confirmed", "交易确认"),
                    ("completed", "已完成"),
                    ("cancelled", "已取消"),
                ],
                db_index=True,
                default="trading",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
