# Generated by Django 4.2.13 on 2026-09-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_conversation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_read",
            field=models.BooleanField(db_index=True, default=False, verbose_name="已读"),
        ),
    ]
