# Generated by Django 4.2.13 on 2026-09-10 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SliderCaptcha",
        ),
    ]
