# Generated by Django 4.2.13 on 2026-09-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_delete_slidercaptcha"),
    ]

    operations = [
        migrations.AddField(
            model_name="verifycode",
            name="attempts",
            field=models.IntegerField(default=0, verbose_name="错误尝试次数"),
        ),
    ]
