# Generated by Django 4.2.13 on 2026-09-07 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="收藏时间"),
                ),
            ],
            options={
                "verbose_name": "收藏",
                "verbose_name_plural": "收藏",
                "db_table": "swap_favorite",
            },
        ),
        migrations.CreateModel(
            name="Goods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="商品名称")),
                ("description", models.TextField(max_length=2000, verbose_name="商品描述")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="价格"
                    ),
                ),
                (
                    "original_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="原价",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("digital", "数码电子"),
                            ("books", "书籍教材"),
                            ("daily", "生活用品"),
                            ("clothing", "服饰鞋包"),
                            ("sports", "运动器材"),
                            ("service", "校园服务"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="大分类",
                    ),
                ),
                (
                    "sub_category",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="小分类"
                    ),
                ),
                (
                    "trade_type",
                    models.CharField(
                        choices=[("pickup", "自提"), ("delivery", "配送")],
                        default="pickup",
                        max_length=20,
                        verbose_name="交易方式",
                    ),
                ),
                (
                    "school",
                    models.CharField(db_index=True, max_length=100, verbose_name="学校"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("on_sale", "在售"),
                            ("sold", "已售出"),
                            ("offline", "已下架"),
                        ],
                        db_index=True,
                        default="on_sale",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("views", models.IntegerField(default=0, verbose_name="浏览量")),
                ("favorites", models.IntegerField(default=0, verbose_name="收藏数")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="发布时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "商品",
                "verbose_name_plural": "商品",
                "db_table": "swap_goods",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GoodsImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="goods/", verbose_name="图片")),
                ("sort", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "goods",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="goods.goods",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品图片",
                "verbose_name_plural": "商品图片",
                "db_table": "swap_goods_image",
                "ordering": ["sort", "id"],
            },
        ),
    ]
