# Generated by Django 4.2.13 on 2026-09-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="goods",
            name="allow_repeat",
            field=models.BooleanField(default=False, verbose_name="允许重复售卖"),
        ),
    ]
