# Generated by Django 4.2.13 on 2026-09-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0003_goods_allow_repeat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goods",
            name="category",
            field=models.CharField(
                choices=[
                    ("digital", "数码电子"),
                    ("books", "书籍教材"),
                    ("daily", "生活用品"),
                    ("clothing", "服饰鞋包"),
                    ("sports", "运动器材"),
                    ("service", "校园服务"),
                    ("snack", "零食餐饮"),
                    ("beauty", "美妆个护"),
                    ("art", "乐器文创"),
                    ("rental", "出租借用"),
                    ("free", "免费赠送"),
                    ("other", "其他"),
                ],
                max_length=20,
                verbose_name="大分类",
            ),
        ),
    ]
