# Generated by Django 4.2.13 on 2026-09-13 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0004_alter_goods_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="ads/", verbose_name="广告图片")),
                (
                    "link",
                    models.URLField(blank=True, max_length=500, verbose_name="跳转链接"),
                ),
                ("start_date", models.DateField(verbose_name="开始日期")),
                ("end_date", models.DateField(verbose_name="结束日期")),
                ("priority", models.IntegerField(default=0, verbose_name="优先级")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "广告",
                "verbose_name_plural": "广告",
                "db_table": "swap_ad",
                "ordering": ["-priority", "id"],
            },
        ),
    ]
