# Generated by Django 4.2.13 on 2026-09-13 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0005_ad"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ad",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="ad",
            name="start_date",
        ),
        migrations.CreateModel(
            name="AdSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="投放日期")),
                (
                    "ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dates",
                        to="goods.ad",
                        verbose_name="广告",
                    ),
                ),
            ],
            options={
                "verbose_name": "广告投放日期",
                "verbose_name_plural": "广告投放日期",
                "db_table": "swap_ad_slot",
                "ordering": ["date"],
                "unique_together": {("ad", "date")},
            },
        ),
    ]
